DROP DATABASE IF EXISTS cryptoUpvoting;
CREATE DATABASE cryptoUpvoting;
USE cryptoUpvoting;

CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;

CREATE TABLE cryptos(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE votes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  cryptoId INT NOT NULL,
  CONSTRAINT userId
    FOREIGN KEY (userId)
    REFERENCES cryptoUpvoting.users (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT cryptoId
    FOREIGN KEY (cryptoId)
    REFERENCES cryptoUpvoting.cryptos (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);