CREATE DATABASE IF NOT EXISTS cryptoUpvoting;
USE cryptoUpvoting;

DROP TABLE IF EXISTS users;

CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;

DROP TABLE IF EXISTS cryptos;

CREATE TABLE cryptos(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS votes;

CREATE TABLE votes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  cryptoId INT NOT NULL,
  CONSTRAINT userId
    FOREIGN KEY (userId)
    REFERENCES cryptoUpvoting.users (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT cryptoId
    FOREIGN KEY (cryptoId)
    REFERENCES cryptoUpvoting.cryptos (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);