version: "3"

services:
  db:
    container_name: upvoting_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: localhost
      MYSQL_DB: cryptoUpvoting